# Generated by Django 5.1.2 on 2025-11-06 03:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Unique patient identifier', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('known_allergies', models.TextField(blank=True, help_text='List any known allergies')),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions and surgeries')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['patient_id'], name='core_patien_patient_c75b93_idx'), models.Index(fields=['last_name', 'first_name'], name='core_patien_last_na_5d3812_idx')],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Link to patient record if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.patient'),
        ),
        migrations.CreateModel(
            name='PatientHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic_bp', models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate (bpm)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Body temperature (°C)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height (cm)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (automatically calculated)', max_digits=5, null=True)),
                ('symptoms', models.TextField(blank=True, help_text='Patient-reported symptoms')),
                ('diagnosis', models.CharField(blank=True, help_text='Diagnosis or condition', max_length=255)),
                ('medications', models.TextField(blank=True, help_text='Medications prescribed')),
                ('notes', models.TextField(blank=True, help_text='Additional clinical notes')),
                ('visit_type', models.CharField(blank=True, help_text='e.g., Routine, Emergency, Follow-up', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='core.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='core.patient')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-record_date'], name='core_patien_patient_66a143_idx'), models.Index(fields=['record_date'], name='core_patien_record__77d954_idx'), models.Index(fields=['department', 'record_date'], name='core_patien_departm_6435f2_idx'), models.Index(fields=['diagnosis'], name='core_patien_diagnos_3f7c98_idx')],
            },
        ),
    ]
