# Generated by Django 5.1.2 on 2025-11-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
